 const sampleContacts = [
  {
    id: 1,
    name: "sana khalid",
    city: "N/A",
    email: "sana@yahoo.com",
    phone: "N/A",
    tag: "Personal",
    avatarType: "person",
  },
  {
    id: 2,
    name: "Camden Regan",
    city: "Holmes Kaden",
    email: "nolan@yahoo.com",
    phone: "+48 +1 (376) 474-3151",
    tag: "Business",
    avatarType: "person",
  },
  {
    id: 3,
    name: "Samson Heidi",
    city: "Brent Zeph",
    email: "doxelipura@mailinator.com",
    phone: "+48 +1 (347) 342-8213",
    tag: "Personal",
    avatarType: "person",
  },
  {
    id: 4,
    name: "jane doe",
    city: "N/A",
    email: "ummeaimonjawed@gmail.com",
    phone: "N/A",
    tag: "Personal",
    avatarType: "person",
  },

  {
    id: 6,
    name: "jane doe",
    city: "N/A",
    email: "ummeaimonjawed@gmail.com",
    phone: "N/A",
    tag: "Supplier",
    avatarType: "person",
  },
  {
    id: 7,
    name: "a b",
    city: "N/A",
    email: "sd@gmail.com",
    phone: "N/A",
    tag: "Personal",
    avatarType: "person",
  },
  {
    id: 8,
    name: "saif",
    city: "N/A",
    email: "saif@yahoo.com",
    phone: "1245678990",
    tag: "Business",
    avatarType: "person",
  },
];
export default sampleContacts;